server:
  port: 9090
dubbo:
  application:
    name: user_service
  registry:
    address: zookeeper://192.168.75.188:2181
  consumer:
    check: false
  protocol:
    port: -1
spring:
  datasource:
    url: jdbc:mysql://localhost/dubbo_user
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    #配置发送方协议
    protocol: smtp
    #配置smtp服务器地址
    host: smtp.sina.cn
    #发送方的邮箱
    username: 18379218654@sina.cn
    #发送方的密码
    password: ping19970613

mybatis:
  #配置扫描映射文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qf.entity